### ISSUE TITLE
Q: How to specify SSL certificate or other options?

### ISSUE THREAD

**Issue by data-henrik** [nakagami/pydrda#11]
I followed the README for testing the connection to a Db2 database with SSL. I am using Db2 on Cloud and its credentials. I received this error:

```
File "/home/xxxxx/.local/lib/python3.6/site-packages/drda/ddm.py", line 236, in read_dds
    raise ConnectionError("invalid DDS packet from socket")
ConnectionError: invalid DDS packet from socket
```

To me it looks like I need to specify more SSL options, e.g., a certificate. Any advice?

**Comment by nakagami** [comment]
Support for authentication with client certificates is not available.

**Comment by nakagami** [comment]
The ssl_ca_certs parameter is now passed to connect.
It is now possible to connect to DB2 on clound.ibm.com by specifying the path to the client certificate file.

This will be included in the next release.

**Comment by nakagami** [comment]
Sory something wrongo so reopen.

**Comment by nakagami** [comment]
This driver can specify the path to the PEM file for client authentication, now.
https://github.com/nakagami/pydrda/commit/56895765655add949ef2aec9303b9b34ada78569

This seems to be a step closer, but I cannot connect to DB2 in IBM cloud.

Even if I specify the path to the PEM file that decodes the certificate_base64 of the IBM cloud service credential, I cannot connect (I get an error) to the DB2 instance.

Can someone please solve the problem of not being able to connect to DB2 in IBM clound.

**Comment by data-henrik** [comment]
I am connecting to Db2 on Cloud just by using the following code:
`return drda.connect(host='my.db2.host.from.config.databases.appdomain.cloud', database='bludb', use_ssl=True, user='userID', password='myPassword', port=54321)`

**Comment by nakagami** [comment]
Thanks, @data-henrik 

Maybe the way I make credencial in my Ibm clound is different.

I hope others (especially with IBM cloud) will report if they can make ssl connections.

**Comment by data-henrik** [comment]
Are you using the lite plan or a standard/enterprise plan?
In the console with the service credentials, this is how it looks when I expand them.

![image](https://github.com/nakagami/pydrda/assets/8414748/0a50a095-c4aa-4ef8-a0b2-5b40ba02bbab)

**Comment by nakagami** [comment]
light Plan.

And, service credentials values are similar.

`certificate_base64` value is decoded and save it in a file name `cert.pem` and set the path to it in the connect argument's `ssl_client_cert_path`.

But it's an error.
```
Traceback (most recent call last):
  File "/Users/nakagami/pydrda/test_db2.py", line 168, in setUp
    self.connection = drda.connect(
                      ^^^^^^^^^^^^^
  File "/Users/nakagami/pydrda/drda/__init__.py", line 122, in connect
    return Connection(host, database, port, user, password, use_ssl, ssl_client_cert_path, db_type, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nakagami/pydrda/drda/connection.py", line 235, in __init__
    secmec, sectkn = self._parse_accsecrd()
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nakagami/pydrda/drda/connection.py", line 143, in _parse_accsecrd
    dss_type, chained, correlation_id, code_point, obj, more_data = ddm.read_dss(self.sock, self.db_type)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nakagami/pydrda/drda/ddm.py", line 236, in read_dss
    raise ConnectionError(f"invalid DSS packet from socket:{binascii.hexlify(b).decode('utf-8')}")
ConnectionError: invalid DSS packet from socket:150303000202
```

And if I don't specify ssl_client_cert_path I get the same error.

(Additional Information)
I set the following environment variables and run test_db2.py
```
DB2_PORT=xxxxx
DB2_USER=xxxxxxxx
DB2_PASSWORD=xxxxxxxxxxxxxxxx
DB2_DATABASE=admin
DB2_SSL_CLIENT_CERT_PATH=/xxx/xxx/cert.pem
DB2_HOST=xxxxx.databases.appdomain.cloud
```
